name: tests-orders

on:
<<<<<<< HEAD
  pull_request:
    paths:
      - "orders/**"
=======
  pull_request
>>>>>>> 92994ca98250510240345a0893f498bb11ca35df

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd orders && npm install && npm run test:ci
